### ISSUE TITLE
Broken when using port different than 80

### ISSUE THREAD

**Issue by miglen** [PHProxy/phproxy#5] opened 2015-12-16 20:47 UTC
Broken when using port different than 80.

**Comment by boppy** [comment] 2016-05-28 14:27
Could you add some more spec? I just reconfigured a site to run on :85 and it still has correct links and upload does also work...

**Comment by PhoenixPeca** [comment] 2018-02-25 00:11
I could not reproduce this issue. I'm closing this for now.

**Closed by PhoenixPeca** 2018-02-25 00:11 UTC
Labels: bug
